language: node_js
os:
  - linux
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - nvm install-latest-npm
script:
  - npm run lint
  - npm run build
  - npm run test
sudo: false
